package com.wyj.auth.dao;

import com.wyj.auth.entity.MallOrder;
import java.util.List;

public interface MallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int insert(MallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    MallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    List<MallOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MallOrder record);
}