package com.wyj.auth.dao;

import com.wyj.auth.entity.po.MallCategory;

import java.util.List;

public interface MallCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbggenerated
     */
    int insert(MallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbggenerated
     */
    MallCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbggenerated
     */
    List<MallCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MallCategory record);
}