spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3307/mallUser?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: 141535

      initialSize: 5 #初始化连接大小
      minIdle: 5     #最小连接池数量
      maxActive: 20  #最大连接池数量
      maxWait: 60000 #获取连接时最大等待时间，单位毫秒
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000   #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 from DUAL  #测试连接
      testWhileIdle: true                  #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      testOnBorrow: false                  #获取连接时执行检测，建议关闭，影响性能
      testOnReturn: false                  #归还连接时执行检测，建议关闭，影响性能
      poolPreparedStatements: false        #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      maxPoolPreparedStatementPerConnectionSize: 20 #开启poolPreparedStatements后生效
      filters: stat,wall,sl4j #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #通过connectProperties属性来打开mergeSql功能;慢SQL记录

  redis:
    database: 1
    host: 127.0.0.1
    password: 141535
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 4
        max-wait: 30000
        min-idle: 0


  rabbitmq:
    #    host: 101.37.69.4
    #    port: 5672
    addresses: 127.0.0.1:5672
    username: admin
    password: 141535
    connection-timeout: 15000
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 5
        ##设置消费端手动确认
        acknowledge-mode: manual
    #开启 confirm 确认机制
    publisher-returns: true
    #开启 return 确认机制
    #    publisher-confirms: true
    #设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
    template:
      mandatory: true
    publisher-confirm-type: correlated


management:
  endpoints:
    web:
      exposure:
        include: '*'


##  ribbon配置
ribbon:
  eureka:
    enabled: true
##  feign配置


## hystrix配置   禁止服务超时时间


  ##  tx-lcn分布式事务解决方案，服务端配置
  #tx-lcn:
  #  client:
  #    manager-address: 127.0.0.1:8070
  #zuul:
  #  routes:
  ##    配置本服务名
  #    service-commodity:
  #      ignored-pattern: /hello/**
  ##      服务映射的路径，通过这个路径可以访问该服务，目的是为了不暴露ip，面向服务。这里zull依赖hystrix和rabbion
  #      path: /commodity/**
  #      serviceId: service-commodity
  #  prefix: /api/**


  ##  rabbitmq配置
#logging:
  #config: classpath:logback-spring-bak.xml
#  file:
#    path: ./logs
#    max-size: 10MB
#    max-history: 7
#  level: info


